import re

with open('src/games.ts', 'r', encoding='utf-8') as f:
    ts_content = f.read()

fixed_bt3_characters = """      { id: 'android-13', name: 'Android 13' },
      { id: 'android-16', name: 'Android 16' },
      { id: 'android-17', name: 'Android 17' },
      { id: 'android-18', name: 'Android 18' },
      { id: 'android-19', name: 'Android 19' },
      { id: 'appule', name: 'Appule' },
      { id: 'baby-vegeta', name: 'Baby Vegeta' },
      { id: 'babidi', name: 'Babidi' },
      { id: 'bardock', name: 'Bardock' },
      { id: 'bojack', name: 'Bojack' },
      { id: 'broly', name: 'Broly' },
      { id: 'burter', name: 'Burter' },
      { id: 'cell', name: 'Cell' },
      { id: 'cell-jr', name: 'Cell Jr' },
      { id: 'chiaotzu', name: 'Chiaotzu' },
      { id: 'cooler', name: 'Cooler' },
      { id: 'cui', name: 'Cui' },
      { id: 'dabura', name: 'Dabura' },
      { id: 'demon-king-piccolo', name: 'Demon King Piccolo' },
      { id: 'devilman', name: 'Devilman' },
      { id: 'dr-gero', name: 'Dr. Gero' },
      { id: 'dr-wheelo', name: 'Dr. Wheelo' },
      { id: 'dodoria', name: 'Dodoria' },
      { id: 'fasha', name: 'Fasha' },
      { id: 'frieza', name: 'Frieza' },
      { id: 'garlic-jr', name: 'Garlic Jr.' },
      { id: 'general-blue', name: 'General Blue' },
      { id: 'ginyu', name: 'Ginyu' },
      { id: 'gohan-kid', name: 'Gohan (Kid)' },
      { id: 'gohan-teen', name: 'Gohan (Teen)' },
      { id: 'gohan-adult', name: 'Gohan (Adult)' },
      { id: 'gohan-future', name: 'Gohan (Future)' },
      { id: 'goku-kid', name: 'Goku (Kid)' },
      { id: 'goku-early', name: 'Goku (Early)' },
      { id: 'goku-mid', name: 'Goku (Mid)' },
      { id: 'goku-end', name: 'Goku (End)' },
      { id: 'goku-gt', name: 'Goku (GT)' },
      { id: 'goten', name: 'Goten' },
      { id: 'gotenks', name: 'Gotenks' },
      { id: 'grandpa-gohan', name: 'Grandpa Gohan' },
      { id: 'great-ape', name: 'Great Ape' },
      { id: 'guldo', name: 'Guldo' },
      { id: 'hercule', name: 'Hercule' },
      { id: 'hirudegarn', name: 'Hirudegarn' },
      { id: 'janemba', name: 'Janemba' },
      { id: 'jeice', name: 'Jeice' },
      { id: 'kid-buu', name: 'Kid Buu' },
      { id: 'kid-chi-chi', name: 'Kid Chi-Chi' },
      { id: 'king-cold', name: 'King Cold' },
      { id: 'king-vegeta', name: 'King Vegeta' },
      { id: 'krillin', name: 'Krillin' },
      { id: 'lord-slug', name: 'Lord Slug' },
      { id: 'majin-buu', name: 'Majin Buu' },
      { id: 'master-roshi', name: 'Master Roshi' },
      { id: 'mecha-frieza', name: 'Mecha Frieza' },
      { id: 'meta-cooler', name: 'Meta-Cooler' },
      { id: 'monster-zarbon', name: 'Monster Zarbon' },
      { id: 'nappa', name: 'Nappa' },
      { id: 'nail', name: 'Nail' },
      { id: 'nuova-shenron', name: 'Nuova Shenron' },
      { id: 'omega-shenron', name: 'Omega Shenron' },
      { id: 'pan', name: 'Pan' },
      { id: 'piccolo', name: 'Piccolo' },
      { id: 'pikkon', name: 'Pikkon' },
      { id: 'pilaf-machine', name: 'Pilaf Machine' },
      { id: 'raditz', name: 'Raditz' },
      { id: 'recoome', name: 'Recoome' },
      { id: 'saibaman', name: 'Saibaman' },
      { id: 'salza', name: 'Salza' },
      { id: 'spopovitch', name: 'Spopovitch' },
      { id: 'super-17', name: 'Super 17' },
      { id: 'super-buu', name: 'Super Buu' },
      { id: 'supreme-kai', name: 'Supreme Kai' },
      { id: 'syn-shenron', name: 'Syn Shenron' },
      { id: 'tambourine', name: 'Tambourine' },
      { id: 'tao-pai-pai', name: 'Tao Pai Pai' },
      { id: 'tapion', name: 'Tapion' },
      { id: 'tenshinhan', name: 'Tenshinhan' },
      { id: 'trunks-sword', name: 'Trunks (Sword)' },
      { id: 'trunks-fighting', name: 'Trunks (Fighting)' },
      { id: 'trunks-future', name: 'Trunks (Future)' },
      { id: 'trunks-kid', name: 'Trunks (Kid)' },
      { id: 'turles', name: 'Turles' },
      { id: 'ultimate-gohan', name: 'Ultimate Gohan' },
      { id: 'uub', name: 'Uub' },
      { id: 'vegeta-scouter', name: 'Vegeta (Scouter)' },
      { id: 'vegeta-early', name: 'Vegeta (Early)' },
      { id: 'vegeta-mid', name: 'Vegeta (Mid)' },
      { id: 'vegeta-end', name: 'Vegeta (End)' },
      { id: 'vegeta-gt', name: 'Vegeta (GT)' },
      { id: 'vegito', name: 'Vegito' },
      { id: 'videl', name: 'Videl' },
      { id: 'yajirobe', name: 'Yajirobe' },
      { id: 'yamcha', name: 'Yamcha' },
      { id: 'zangya', name: 'Zangya' }"""

game_block_regex = r"(id:\s*['\"]dragon-ball-z-budokai-tenkaichi-3['\"].*?characters:\s*\[\s*)(.*?)(\s*\])"
gmatch = re.search(game_block_regex, ts_content, re.DOTALL)
if gmatch:
    ts_content = ts_content[:gmatch.start()] + gmatch.group(1) + "\n" + fixed_bt3_characters + "\n" + gmatch.group(3) + ts_content[gmatch.end():]
    with open('src/games.ts', 'w', encoding='utf-8') as f:
        f.write(ts_content)
    print("Fixed Dragon Ball Z Budokai Tenkaichi 3 characters.")
else:
    print("Could not find BT3 block in src/games.ts.")
